version: '3.8'

services:
  silent-auth-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: silent-auth-app
    ports:
      - "80:80" -"443:443"
    environment:
      - NODE_ENV=production
      - REACT_APP_AUTH_ENDPOINT=https://silent-auth.u.com.my
      - REACT_APP_CLIENT_ID=${CLIENT_ID:-your-client-id}
      - REACT_APP_REDIRECT_URI=${REDIRECT_URI:-http://localhost/auth/callback}
      - REACT_APP_SCOPE=${SCOPE:-openid profile email}
    volumes:
      # Optional: Mount SSL certificates
      # - ./ssl:/etc/nginx/ssl:ro
      # Optional: Mount custom nginx config
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Optional: Mount logs for debugging
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - silent-auth-network
    labels:
      - "traefik.enable=true" -"traefik.http.routers.silent-auth.rule=Host(`your-domain.com`)" -"traefik.http.routers.silent-auth.tls=true" -"traefik.http.routers.silent-auth.tls.certresolver=letsencrypt"

networks:
  silent-auth-network:
    driver: bridge

# Optional: Add a reverse proxy for production
# services:
#   traefik:
#     image: traefik:v3.0
#     container_name: traefik
#     command:
#       - "--api.insecure=true" #       -"--providers.docker=true" #       -"--providers.docker.exposedbydefault=false" #       -"--entrypoints.web.address=:80" #       -"--entrypoints.websecure.address=:443" #       -"--certificatesresolvers.letsencrypt.acme.tlschallenge=true" #       -"--certificatesresolvers.letsencrypt.acme.email=your-email@domain.com" #       -"--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
#     ports:
#       - "80:80" #       -"443:443" #       -"8080:8080"
#     volumes:
#       - "/var/run/docker.sock:/var/run/docker.sock:ro"
#       - "./letsencrypt:/letsencrypt"
#     networks:
#       - silent-auth-network